### ISSUE TITLE
Specific Settings Required

### ISSUE THREAD

**Issue by Bolt7** [itamarcu/pf2e-modifiers-matter#1]
The module only works when "Show results on attacks and saves" is set to "All" in the Metagame Information section of the System Settings.

Expected behaviour: when it's set to GM or Owner, everyone that permission includes (ie. those who can see the degree of success) can see the highlights.

Current behaviour: when it's set to GM or Owner, nobody can see the highlights, despite some seeing the degree of success.

**Comment by itamarcu** [comment]
Thanks for the report!  Fixed in v1.0.0.
