### ISSUE TITLE
"k is not defined" when updating from 1.4.6 to 1.5.0

### ISSUE THREAD

**Issue by dhemery** [itamarcu/pf2e-modifiers-matter#14]
When I try to update Modifiers Matter from 1.4.6 to 1.5.0, I get an error message: “k is not defined”. See the attached image.

My system:
- macOS: 12.5
- Google Chrome: Version 104.0.5112.79 (Official Build) (arm64)
- Foundry: Version 9 - Build 269
- Pathfinder 2nd Edition: 3.13.5.16

<img width="1142" alt="modifiers-matter-update-error" src="https://user-images.githubusercontent.com/120657/184506487-9886d090-eb39-4639-a691-1ea322099255.png">

**Comment by itamarcu** [comment]
Version 1.5.0 is compatible only with Foundry V10 - I'm not sure why this is even allowing you to try, but it'd be a foundry bug.
