### ISSUE TITLE
Modifiers not being highlighted

### ISSUE THREAD

**Issue by KLSteinwand** [itamarcu/pf2e-modifiers-matter#3]
As title says, the modifiers are not highlighting with PF2e system v2.19.1, even with no other modules active.
![Modifiers](https://user-images.githubusercontent.com/87665999/142900764-d6da1a6c-6ad0-449a-bd42-dcda49c90399.PNG)

**Comment by itamarcu** [comment]
Looks like this is incompatibility with PF2e tweaks by Ustin:

![image](https://user-images.githubusercontent.com/6516621/143026170-4593273a-3fc7-425a-b57b-ac6bd6adaa42.png)

**Comment by itamarcu** [comment]
Fixed in v1.0.4
