### ISSUE TITLE
Modifiers to attack roll not highlighting on changed outcome

### ISSUE THREAD

**Issue by DuskyVoltage** [itamarcu/pf2e-modifiers-matter#4]
Modifiers to the attack roll (such as bless/inspire courage/frightened) aren't being highlighted when they change an outcome. Modifiers to target AC are being correctly highlighted when they're relevant.

Examples:
Frightened causing a miss:
![MdYWfWJ](https://user-images.githubusercontent.com/9156437/150829975-4f4ed19b-ff28-4ade-893b-12b17bbfc083.png)

Bless causing a hit:
![FeOq25I](https://user-images.githubusercontent.com/9156437/150830062-522fd9e1-6dc5-4f4d-b57f-81c5a371826c.png)

AC modifiers correctly being highlighted:
![lnJ0XDM](https://user-images.githubusercontent.com/9156437/150830109-6e7acbae-f54e-4b63-a90f-76a12fbccc69.png)

By the way, excellent module, thanks for your time!

**Comment by itamarcu** [comment]
Fixed on version 1.1.0!
