### ISSUE TITLE
Not highlighting attack modifiers.

### ISSUE THREAD

**Issue by leerhund** [itamarcu/pf2e-modifiers-matter#5]
Foundry v9.242
PF2e 3.2.2.10109

Module is not highlighting all modifiers.
Effects altering the target's AC seem to be highlighting properly, but ones affecting the attack are not. 
![image](https://user-images.githubusercontent.com/95336883/150830543-be3e1f41-7949-4ae3-b070-41852501591a.png)

**Comment by leerhund** [comment]
Opened issue simultaneously.

**Comment by itamarcu** [comment]
Duplicate of #4, fixed on version 1.1.0!
