### ISSUE TITLE
The circumstance bonuses shown always seems to indicate "Flat-Footed" instead of the correct bonus

### ISSUE THREAD

**Issue by git-kor-av** [itamarcu/pf2e-modifiers-matter#6]
In the example below I had one PC enable Nimble Dodge to gain a +2 AC (Korfel).  Then Kelomir attacked Korfel.  Korfel was not flat-footed (nor was Kelomir though it shouldn't matter).
![Screenshot 2022-02-19 162448](https://user-images.githubusercontent.com/32276185/154820084-cbeb4646-49b8-4b0f-938a-1b40aa0a8586.jpg)

**Comment by itamarcu** [comment]
Fixed in v1.2.0 !
