### ISSUE TITLE
Release 1.3.0 not working with current version of PF2E System

### ISSUE THREAD

**Issue by LolipopCandy** [itamarcu/pf2e-modifiers-matter#8]
Foundry V9 build 249
PF2E system 3.5.2.10605

Tested in a new world with no other modules active and it's not working.
![image](https://user-images.githubusercontent.com/94734833/156109708-a0d03484-e6c8-4949-975e-4ba2379df91e.png)

also it looks like this in the Module settings if it helps
![image](https://user-images.githubusercontent.com/94734833/156109884-31f78527-b541-40a4-9391-eb8fab2c60aa.png)

**Comment by itamarcu** [comment]
v1.3.2 should have it fixed.  Thanks!
