### ISSUE TITLE
Modifiers Not Showing Up When Relevant - PF2e v3.5.x compatibility

### ISSUE THREAD

**Issue by DariusWolfe** [itamarcu/pf2e-modifiers-matter#9]
I recently updated Foundry, PF2E and this mod, and the modifiers no longer show up on the chat card when they should. 

Browser: Built-in Foundry VTT
FVTT Version: 9 Build 251
PF2E Version: 3.5.2.10605
Modules Installed: 
 - Pf2E Modifiers Matter

![image](https://user-images.githubusercontent.com/63481633/156481503-e35626d6-4642-472c-bddd-88438feeeec5.png)
In the attached Screenshot, test (gold border icon) has struck Orc Warrior by exceeding its AC by 1. Its natural AC is 18, but it is currently Frightened 2, lowering it to 16. This should show that the Frightened condition was relevant to the successful strike, but it does not.

**Comment by itamarcu** [comment]
To clarify, which version of this module is it?

And do you see errors n the console log (F12)?

**Comment by itamarcu** [comment]
You were right;  the latest PF2e system update broke the module.  I'm on it!

**Comment by itamarcu** [comment]
Fixed in v1.4.0
